In [1]:
import pennylane as qml
import pennylane.numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('classic')

## Exercise 1

In [2]:
dev = qml.device("default.qubit", wires=1)

@qml.qnode(dev)
def apply_z_to_plus():
    """Write a circuit that applies PauliZ to the |+> state and returns
    the state.

    Returns:
        array[complex]: The state of the qubit after the operations.
    """

    ##################
    # YOUR CODE HERE #
    ##################

    # CREATE THE |+> STATE
    qml.Hadamard(0)
    # APPLY PAULI Z
    qml.PauliZ(0)
    # RETURN THE STATE
    return qml.state()

print(apply_z_to_plus())

[ 0.70710678+0.j -0.70710678+0.j]


## Exercise 2

In [3]:
dev = qml.device("default.qubit", wires=1)

@qml.qnode(dev)
def fake_z():
    """Use RZ to produce the same action as Pauli Z on the |+> state.

    Returns:
        array[complex]: The state of the qubit after the operations.
    """

    ##################
    # YOUR CODE HERE #
    ##################

    # CREATE THE |+> STATE
    qml.Hadamard(0)
    # APPLY RZ
    qml.RZ(np.pi,0)
    # RETURN THE STATE
    return qml.state()

print(fake_z())

[4.32978028e-17-0.70710678j 4.32978028e-17+0.70710678j]


## Exercise 3

In [8]:
dev = qml.device('default.qubit', wires=3)

@qml.qnode(dev)
def too_many_ts():
    """You can implement the original circuit here as well, it may help you with
    testing to ensure that the circuits have the same effect.

    Returns:
        array[float]: The measurement outcome probabilities.
    """
    qml.Hadamard(0)
    qml.T(0)
    qml.T(0)
    qml.Hadamard(0)
    qml.adjoint(qml.T(0))
    qml.adjoint(qml.T(0))
    qml.Hadamard(0)
    
    qml.Hadamard(1)
    qml.T(1)
    qml.Hadamard(1)
    qml.T(1)
    qml.T(1)
    qml.T(1)
    qml.T(1)
    qml.Hadamard(1)
    
    qml.Hadamard(2)
    qml.adjoint(qml.T(2))
    qml.Hadamard(2)
    qml.adjoint(qml.T(2))
    qml.adjoint(qml.T(2))
    qml.adjoint(qml.T(2))
    qml.Hadamard(2)
    return qml.probs(wires=[0, 1, 2])

@qml.qnode(dev)
def just_enough_ts():
    """
    Implement an equivalent circuit as the above with the minimum number of 
    T and T^\dagger gates required.

    Returns:
        array[float]: The measurement outcome probabilities.
    """

    ##################
    # YOUR CODE HERE #
    ##################

    # IMPLEMENT THE CIRCUIT, BUT COMBINE AND OPTIMIZE THE GATES
    # TO MINIMIZE THE NUMBER OF TS


    return qml.probs(wires=[0, 1, 2])

##################
# YOUR CODE HERE #
##################

original_depth = 0
original_t_count = 0
original_t_depth = 0

optimal_depth = 0
optimal_t_count = 0
optimal_t_depth = 0


<>:39: SyntaxWarning: invalid escape sequence '\d'
<>:39: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_339479/2348414558.py:39: SyntaxWarning: invalid escape sequence '\d'
  """


In [9]:
specs1 = qml.specs(too_many_ts)
specs1()

{'resources': Resources(num_wires=3, num_gates=22, gate_types=defaultdict(<class 'int'>, {'Hadamard': 9, 'T': 7, 'Adjoint(T)': 6}), gate_sizes=defaultdict(<class 'int'>, {1: 22}), depth=8, shots=Shots(total_shots=None, shot_vector=())),
 'errors': {},
 'num_observables': 1,
 'num_diagonalizing_gates': 0,
 'num_trainable_params': 0,
 'num_device_wires': 3,
 'device_name': 'default.qubit',
 'expansion_strategy': 'gradient',
 'gradient_options': {},
 'interface': 'auto',
 'diff_method': 'best',
 'gradient_fn': 'backprop'}

In [27]:
H = [1,1,1,-1]
H = [h*(1+0j)*(1/2**(0.5)) for h in H]
H = np.reshape(H, (2,2))
S = np.array([[1,0],[0,1j]])
T = S = np.array([[1,0],[0,1/2**(0.5)*(1+1j)]])
H, S, T

(tensor([[ 0.70710678+0.j,  0.70710678+0.j],
         [ 0.70710678+0.j, -0.70710678+0.j]], requires_grad=True),
 tensor([[1.        +0.j        , 0.        +0.j        ],
         [0.        +0.j        , 0.70710678+0.70710678j]], requires_grad=True),
 tensor([[1.        +0.j        , 0.        +0.j        ],
         [0.        +0.j        , 0.70710678+0.70710678j]], requires_grad=True))

In [33]:
H@S@H@np.conjugate(S)@H

tensor([[ 0.5       +2.77555756e-17j,  0.70710678+5.00000000e-01j],
        [ 0.70710678-5.00000000e-01j, -0.5       -2.77555756e-17j]], requires_grad=True)

In [4]:
dev = qml.device("default.qubit", wires=1)

@qml.qnode(dev)
def many_rotations():
    """Implement the circuit depicted above and return the quantum state.

    Returns:
        array[complex]: The state of the qubit after the operations.
    """

    ##################
    # YOUR CODE HERE #
    ##################

    # IMPLEMENT THE CIRCUIT
    qml.Hadamard(0)
    qml.S(0)
    qml.adjoint(qml.T)(0)
    qml.RZ(0.3,0)
    # RETURN THE STATE
    qml.adjoint(qml.S)(0)
    return qml.state()
print(many_rotations())

[0.69916673-0.10566872j 0.56910461-0.41966647j]
